name: Trigger auto deployment for dockerappsamermalekshedi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dockerappsamermalekshedi-AutoDeployTrigger-1e6db78d-454f-4f3d-b868-1c03d13c6d92.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: samershedimalek.azurecr.io
          username: ${{ secrets.DOCKERAPPSAMERMALEKSHEDI_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERAPPSAMERMALEKSHEDI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: samershedimalek.azurecr.io/dockerappsamermalekshedi:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DOCKERAPPSAMERMALEKSHEDI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dockerappsamermalekshedi -g OurContainers --server samershedimalek.azurecr.io --username  ${{ secrets.DOCKERAPPSAMERMALEKSHEDI_REGISTRY_USERNAME }} --password ${{ secrets.DOCKERAPPSAMERMALEKSHEDI_REGISTRY_PASSWORD }}
            az containerapp update -n dockerappsamermalekshedi -g OurContainers --image samershedimalek.azurecr.io/dockerappsamermalekshedi:${{ github.sha }}
